/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAveragesChart: typeof import('./src/components/dashboard/AppAveragesChart.vue')['default']
    AppCompetencyCard: typeof import('./src/components/AppCompetencyCard.vue')['default']
    AppCtaButton: typeof import('./src/components/AppCtaButton.vue')['default']
    AppLatestScores: typeof import('./src/components/AppLatestScores.vue')['default']
    AppSubmitScore: typeof import('./src/components/AppSubmitScore.vue')['default']
    DashboardDetail: typeof import('./src/components/DashboardDetail.vue')['default']
    DashboardDetailAverages: typeof import('./src/components/DashboardDetailAverages.vue')['default']
    DashboardDetailHighest: typeof import('./src/components/DashboardDetailHighest.vue')['default']
    DashboardDetailRadar: typeof import('./src/components/dashboard/DashboardDetailRadar.vue')['default']
    DashboardDetailTimeline: typeof import('./src/components/dashboard/DashboardDetailTimeline.vue')['default']
    DashboardTable: typeof import('./src/components/DashboardTable.vue')['default']
    DashboardTableContent: typeof import('./src/components/DashboardTableContent.vue')['default']
    DashboardTableTitle: typeof import('./src/components/DashboardTableTitle.vue')['default']
    HelpGuide: typeof import('./src/components/HelpGuide.vue')['default']
    HelpSupport: typeof import('./src/components/HelpSupport.vue')['default']
    LearnerCompetencies: typeof import('./src/components/LearnerCompetencies.vue')['default']
    LearnerCompetency: typeof import('./src/components/learner/LearnerCompetency.vue')['default']
    LearnerCompetencyDetail: typeof import('./src/components/learner/LearnerCompetencyDetail.vue')['default']
    LearnerDetail: typeof import('./src/components/LearnerDetail.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TheToast: typeof import('./src/components/TheToast.vue')['default']
  }
}
